In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('data_extraction.csv')

In [31]:
df

    Unnamed: 0     pos_x    pscale
0            0  0.000000  1.000000
1            1  0.342143  0.948890
2            2  0.684286  0.897778
3            3  1.026429  0.846667
4            4  1.368571  0.795556
5            5  1.710714  0.744445
6            6  2.052857  0.693334
7            7  2.395000  0.642223
8            8  2.737143  0.591111
9            9  3.079286  0.540000
10          10  3.421429  0.488889
11          11  3.763572  0.437778
12          12  4.105714  0.386667
13          13  4.447857  0.335556
14          14  4.790000  0.284444

In [32]:
df = df.drop("Unnamed: 0",axis=1)

In [33]:
from sklearn.linear_model import LinearRegression
#Prepare data
X_POS = np.arange(len(df)).reshape(-1,1)
Y_POS = df['pos_x'].values
X_POS, Y_POS

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14]]),
 array([0.        , 0.34214285, 0.6842857 , 1.02642858, 1.3685714 ,
        1.71071434, 2.05285716, 2.39499998, 2.7371428 , 3.07928562,
        3.42142868, 3.7635715 , 4.10571432, 4.44785738, 4.78999996]))

In [61]:
import pickle
model_pos = LinearRegression()
model_pos.fit(X_POS, Y_POS)
next_pos_x = model_pos.predict([[len(df)]])[0]
next_pos_x

with open("model_pos.pkl","wb") as f:
  pickle.dump(model_pos,f)

In [62]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=3)
X_PSCALE = poly.fit_transform(np.arange(len(df)).reshape(-1,1))
Y_PSCALE = df["pscale"].values
model_pscale = LinearRegression()
model_pscale.fit(X_PSCALE,Y_PSCALE)
next_pscale = model_pscale.predict(poly.transform(([[len(df)]])))[0]

with open("model_pscale.pkl","wb") as f:
  pickle.dump(model_pscale,f)

In [36]:
next_pscale

np.float64(0.23333353378396227)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.preprocessing import MinMaxScaler

In [38]:
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)
scaled

array([[0.        , 1.        ],
       [0.07142857, 0.92857244],
       [0.14285714, 0.85714371],
       [0.21428572, 0.78571515],
       [0.28571428, 0.7142865 ],
       [0.35714287, 0.64285785],
       [0.42857144, 0.57142921],
       [0.5       , 0.50000048],
       [0.57142856, 0.42857192],
       [0.64285713, 0.35714319],
       [0.71428574, 0.28571458],
       [0.78571431, 0.21428594],
       [0.85714287, 0.14285729],
       [0.92857149, 0.07142865],
       [1.        , 0.        ]])

In [39]:
def create_sequences(data,seq_length):
  x,y=[],[]
  for i in range(len(data)-seq_length):
    x.append(data[i:(i+seq_length)])
    y.append(data[i+seq_length])
  return np.array(x),np.array(y)

In [41]:
sequence_length = 3
x,y = create_sequences(scaled,sequence_length)

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
model = Sequential()
model.add(LSTM(50, activation='relu',input_shape=(x.shape[1],x.shape[2])))
model.add(Dense(2))

model.compile(optimizer='adam',loss='mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [46]:
model.fit(x,y,epochs=200,verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - loss: 0.2617
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 0.2554
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.2491
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.2429
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 0.2366
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.2304
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 0.2242
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 0.2180
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - loss: 0.2119
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 0.2058
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - loss: 0.1996
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.1935
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 0.1874
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - loss: 0.1812
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - loss: 0.1751
Epoch 16/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 0.1689
Epoch 17/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 0.1628
Epoch 18/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 0.1567
Epoch 19/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - loss: 0.1506
Epoch 20/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.1445
Epoch 21/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.1385
Epoch 22/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - loss: 0.1324
Epoch 23/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.1265
Epoch 24/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.1205
Epoch 25/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.1147
Epoch 26/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.1089
Epoch 27/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.1032
Epoch 28/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0976
Epoch 29/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 0.0921
Epoch 30/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0867
Epoch 31/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0815
Epoch 32/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 0.0765
Epoch 33/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0717
Epoch 34/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0671
Epoch 35/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0627
Epoch 36/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0586
Epoch 37/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0548
Epoch 38/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0513
Epoch 39/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0481
Epoch 40/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0452
Epoch 41/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0425
Epoch 42/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 245ms/step - loss: 0.0402
Epoch 43/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step - loss: 0.0381
Epoch 44/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step - loss: 0.0363
Epoch 45/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 274ms/step - loss: 0.0347
Epoch 46/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 0.0333
Epoch 47/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0320
Epoch 48/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 0.0308
Epoch 49/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 0.0297
Epoch 50/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.0286
Epoch 51/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0275
Epoch 52/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 0.0264
Epoch 53/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step - loss: 0.0253
Epoch 54/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - loss: 0.0242
Epoch 55/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 0.0230
Epoch 56/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.0219
Epoch 57/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 0.0207
Epoch 58/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.0196
Epoch 59/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 0.0185
Epoch 60/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.0174
Epoch 61/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0164
Epoch 62/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0154
Epoch 63/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.0144
Epoch 64/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.0135
Epoch 65/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 0.0126
Epoch 66/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 0.0118
Epoch 67/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.0109
Epoch 68/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 0.0102
Epoch 69/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 0.0094
Epoch 70/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0087
Epoch 71/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0080
Epoch 72/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0074
Epoch 73/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0067
Epoch 74/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0061
Epoch 75/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0056
Epoch 76/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0050
Epoch 77/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0045
Epoch 78/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0041
Epoch 79/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0036
Epoch 80/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0032
Epoch 81/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0028
Epoch 82/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0025
Epoch 83/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0022
Epoch 84/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0019
Epoch 85/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0016
Epoch 86/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0014
Epoch 87/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0012
Epoch 88/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 9.7072e-04
Epoch 89/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 8.1111e-04
Epoch 90/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 6.7542e-04
Epoch 91/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 5.6239e-04
Epoch 92/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 4.7038e-04
Epoch 93/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 3.9734e-04
Epoch 94/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 3.4088e-04
Epoch 95/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.9845e-04
Epoch 96/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.6740e-04
Epoch 97/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 2.4529e-04
Epoch 98/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.2993e-04
Epoch 99/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.1952e-04
Epoch 100/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.1268e-04
Epoch 101/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 2.0844e-04
Epoch 102/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2.0615e-04
Epoch 103/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 2.0540e-04
Epoch 104/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 2.0585e-04
Epoch 105/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.0723e-04
Epoch 106/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.0917e-04
Epoch 107/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 2.1131e-04
Epoch 108/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2.1319e-04
Epoch 109/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 2.1434e-04
Epoch 110/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.1450e-04
Epoch 111/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.1340e-04
Epoch 112/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.1096e-04
Epoch 113/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2.0718e-04
Epoch 114/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2.0217e-04
Epoch 115/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.9617e-04
Epoch 116/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1.8954e-04
Epoch 117/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.8257e-04
Epoch 118/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.7552e-04
Epoch 119/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.6855e-04
Epoch 120/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.6168e-04
Epoch 121/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.5514e-04
Epoch 122/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 1.4899e-04
Epoch 123/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.4326e-04
Epoch 124/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 1.3797e-04
Epoch 125/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.3315e-04
Epoch 126/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.2861e-04
Epoch 127/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.2442e-04
Epoch 128/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.2067e-04
Epoch 129/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.1737e-04
Epoch 130/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.1449e-04
Epoch 131/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.1200e-04
Epoch 132/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.0984e-04
Epoch 133/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.0794e-04
Epoch 134/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.0626e-04
Epoch 135/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.0473e-04
Epoch 136/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.0332e-04
Epoch 137/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 1.0199e-04
Epoch 138/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 1.0071e-04
Epoch 139/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 9.9483e-05
Epoch 140/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 9.8293e-05
Epoch 141/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 9.7131e-05
Epoch 142/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 9.6001e-05
Epoch 143/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 9.4898e-05
Epoch 144/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.3812e-05
Epoch 145/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 9.2734e-05
Epoch 146/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 9.1655e-05
Epoch 147/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 9.0569e-05
Epoch 148/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 8.9475e-05
Epoch 149/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 8.8376e-05
Epoch 150/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 8.7318e-05
Epoch 151/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 8.6265e-05
Epoch 152/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 8.5226e-05
Epoch 153/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 8.4206e-05
Epoch 154/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 8.3210e-05
Epoch 155/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 8.2243e-05
Epoch 156/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 8.1305e-05
Epoch 157/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 8.0395e-05
Epoch 158/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 7.9508e-05
Epoch 159/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 7.8638e-05
Epoch 160/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 7.7788e-05
Epoch 161/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 7.6967e-05
Epoch 162/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 7.6182e-05
Epoch 163/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 7.5438e-05
Epoch 164/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 7.4709e-05
Epoch 165/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 7.3988e-05
Epoch 166/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 7.3280e-05
Epoch 167/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 7.2584e-05
Epoch 168/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 7.1899e-05
Epoch 169/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 7.1223e-05
Epoch 170/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 7.0554e-05
Epoch 171/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 6.9893e-05
Epoch 172/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 6.9237e-05
Epoch 173/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 6.8586e-05
Epoch 174/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 6.7941e-05
Epoch 175/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 6.7301e-05
Epoch 176/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 6.6667e-05
Epoch 177/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 6.6038e-05
Epoch 178/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 6.5415e-05
Epoch 179/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 6.4797e-05
Epoch 180/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 6.4185e-05
Epoch 181/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 6.3580e-05
Epoch 182/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 6.2979e-05
Epoch 183/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 6.2381e-05
Epoch 184/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 6.1784e-05
Epoch 185/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 6.1193e-05
Epoch 186/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 6.0607e-05
Epoch 187/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 6.0027e-05
Epoch 188/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 5.9453e-05
Epoch 189/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5.8883e-05
Epoch 190/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5.8318e-05
Epoch 191/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 5.7758e-05
Epoch 192/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 5.7211e-05
Epoch 193/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5.6676e-05
Epoch 194/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5.6145e-05
Epoch 195/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5.5617e-05
Epoch 196/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 5.5093e-05
Epoch 197/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 5.4572e-05
Epoch 198/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 5.4054e-05
Epoch 199/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 5.3539e-05
Epoch 200/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5.3028e-05

In [50]:
last_seq = x[-1:]
predicted = model.predict(last_seq)

predicted_original_scale = scaler.inverse_transform(predicted)
print("Predicted next position:",predicted_original_scale[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Predicted next position: [4.822714  0.2950645]

In [51]:
df

       pos_x    pscale
0   0.000000  1.000000
1   0.342143  0.948890
2   0.684286  0.897778
3   1.026429  0.846667
4   1.368571  0.795556
5   1.710714  0.744445
6   2.052857  0.693334
7   2.395000  0.642223
8   2.737143  0.591111
9   3.079286  0.540000
10  3.421429  0.488889
11  3.763572  0.437778
12  4.105714  0.386667
13  4.447857  0.335556
14  4.790000  0.284444

In [58]:
#recursive pred
num_predictions = 5
predictions = []
last_sequence = x[-1:]
for _ in range(num_predictions):
  predicted = model.predict(last_sequence)
  predictions.append(predicted[0])
  predicted_reshaped = predicted.reshape(1,1,2)
  last_sequence = np.concatenate((last_sequence[:,1:,:],predicted_reshaped),axis=1)

predictions = scaler.inverse_transform(predictions)
print("Predictions:",predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Predictions: [[4.82271384 0.29506453]
 [5.12151554 0.27114856]
 [5.43588704 0.25261269]
 [5.76959816 0.23752305]
 [6.09838887 0.22377041]]

In [60]:
df.tail()

       pos_x    pscale
10  3.421429  0.488889
11  3.763572  0.437778
12  4.105714  0.386667
13  4.447857  0.335556
14  4.790000  0.284444